Database:
  #Player data storage type, MYSQL or SQLITE
  Type: SQLITE
  MYSQL:
    Host: localhost
    Port: 3306
    Database: InteractionVisualizer
    Username: mysql
    Password: password

Messages:
  NoPermission: "&cYou do not have permission to use that command!"
  Reload: "&aInteractionVisualizer sucessfully reloaded!"
  Toggle:
    Usage: "&cUsage: /interactionvisualizer toggle <itemstand/itemdrop/hologram>"
    Modes: "&cToggle Modes: itemstand, itemdrop, hologram"
    Console: "&cPlease provide a player name: /interactionvisualizer toggle <mode> [player]"
    ToggleOn: "&aToggled %s on"
    ToggleOff: "&eToggled %s off"
    PlayerNotFound: "&cThe player is not online!"

GarbageCollector:
  #How often should the plugin sweep up and remove tile entity blocks that no longer needs to be tracked
  #Measured in ticks, 20 ticks = 1 second
  #Adjust this if your server is unable to handle fast updates
  Period: 600

TileEntityUpdate:
  #How fast should the plugin collect changes to tile entities since the last check
  #The plugin will first collect all active chunks (defined in CheckingRange)
  #Then load all the tile entities in those chunks in async
  #Note that the period is not just ChunksPerTick, it is a few ticks longer than that to deal with other things
  #Adjust this if your server is unable to handle fast updates
  ChunksPerTick: 4
  #Only turn this to false if you are having problems
  LoadTileEntitiesAsync: true
  #The range in which tile entities in chunks around the player are checked
  #A range of 0 means only the chunk where the player is standing in is checked
  CheckingRange: 1

LightUpdate:
  #How often should the plugin update the light level a block that requires it is used
  #Measured in ticks, 20 ticks = 1 second
  #Adjust this if your server is unable to handle fast light updates
  Period: 10

#Enable InteractionVisualizer for these blocks
Blocks:
  Anvil:
    Enabled: true
  Beacon:
    Enabled: true
    #How often should the plugin check for block updates
    #Measured in ticks, 20 ticks = 1 second
    #Adjust this if your server is unable to handle fast updates / can handle faster updates
    CheckingPeriod: 20
  BeeHive:
    Enabled: true
    CheckingPeriod: 20
    Options:
      HoneyLevelCharacter: "\u2b1b"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoCampfireColor: "&c"
      BeeCountText: "&e{Current}&6/{Max}"
  BeeNest:
    Enabled: true
    CheckingPeriod: 20
    Options:
      HoneyLevelCharacter: "\u2b1b"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoCampfireColor: "&c"
      BeeCountText: "&e{Current}&6/{Max}"
  BlastFurnace:
    Enabled: true
    CheckingPeriod: 10
    Options:
      ProgressBarCharacter: "\u258e"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoFuelColor: "&c"
      ProgressBarLength: 10
      AmountPending: " &7+{Amount}"
  BrewingStand:
    Enabled: true
    CheckingPeriod: 20
    Options:
      ProgressBarCharacter: "\u258e"
      EmptyColor: "&7"
      FilledColor: "&6"
      NoFuelColor: "&c"
      ProgressBarLength: 10
  Campfire:
    Enabled: true
    CheckingPeriod: 20
    Options:
      ProgressBarCharacter: "\uff5c"
      EmptyColor: "&7"
      FilledColor: "&e"
      ProgressBarLength: 10
  CartographyTable:
    Enabled: true
  Chest:
    Enabled: true
  Conduit:
    Enabled: true
    CheckingPeriod: 20
  CraftingTable:
    Enabled: true
  Dispenser:
    Enabled: true
  DoubleChest:
    Enabled: true
  Dropper:
    Enabled: true
  EnchantmentTable:
    Enabled: true
  EnderChest:
    Enabled: true
  Furnace:
    Enabled: true
    CheckingPeriod: 20
    Options:
      ProgressBarCharacter: "\u258e"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoFuelColor: "&c"
      ProgressBarLength: 10
      AmountPending: " &7+{Amount}"
  Grindstone:
    Enabled: true
  Hopper:
    Enabled: true
  JukeBox:
    Enabled: true
    CheckingPeriod: 20
  Lectern:
    Enabled: true
    CheckingPeriod: 20
    Options:
      Line1: "&e{Title}"
      Line2: "&7&o- {Author}"
  Loom:
    Enabled: true
  NoteBlock:
    Enabled: true
  ShulkerBox:
    Enabled: true
  SmithingTable:
    Enabled: true
  Smoker:
    Enabled: true
    CheckingPeriod: 10
    Options:
      ProgressBarCharacter: "\u258e"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoFuelColor: "&c"
      ProgressBarLength: 10
      AmountPending: " &7+{Amount}"
  SoulCampfire:
    Enabled: true
    CheckingPeriod: 20
    Options:
      ProgressBarCharacter: "\uff5c"
      EmptyColor: "&7"
      FilledColor: "&b"
      ProgressBarLength: 10
  Spawner:
    Enabled: true
    CheckingPeriod: 20
    Options:
      ProgressBarCharacter: "\u258e"
      EmptyColor: "&c"
      FilledColor: "&a"
      ProgressBarLength: 10
      SpawnRange: " &f{SpawnRange}m"
  Stonecutter:
    Enabled: true

Entities:
  Villager: 
    Enabled: true

#Enable these modules for InteractionVisualizer displays
#ItemStand represents all displays using armorstands and itemframes
#ItemDrop represents all displays using dropped items
#Hologram represents all holograpgic displays using armorstands
Modules:
  ItemStand:
    Enabled: true
  ItemDrop:
    Enabled: true
  Hologram:
    Enabled: true

Settings:
  UseHandSwingAnimation: true
  PickupAnimationPlayerYOffset: 0
  DisabledWorlds: []
  HideIfViewObstructed: false
  #The default language
  #Doesn't do anything on Minecraft 1.13+
  Language: en_us

Options:
  Updater: true
  DownloadLanguageFiles: true
  
